/* First Mate Home — what My First Mate says at four moments of the day. Synthetic data only.
   Entities (First Mates, watchers, chats, machines, reviews) come from ../data.js; each moment overrides
   their state and adds the assistant's own words. Tokens like {fm:f-passkey} render as smart chips:
   fm = First Mate, w = watcher, m = machine, c = chat, r = Herdr review, pr = pull request number. */
(() => {
  'use strict';

  const MOMENTS = {
    morning: {
      label: 'Morning',
      note: 'Friday, 9:04 AM. You just sat down. Things happened overnight; two got stuck.',
      greeting: 'Good morning.',
      when: 'Friday, October 2 · 9:04 AM',
      away: 'You were away 13 hours',
      mood: 'attentive',
      overrides: {
        features: {},
        machines: {},
        watchers: {},
      },
      lead: [
        'Mostly a quiet night. {fm:f-csv} finished and its PR is green, and {fm:f-snap} is down to three stubborn tests.',
        'Two things got stuck while you were away, so they’re first.',
      ],
      topTitle: 'Start with these',
      top: [
        { id: 't-docs', kind: 'fm', ref: 'f-docs', why: 'Blocked since 2:14 AM', tone: 'alert',
          text: 'Staging rejected the new search schema. It needs the staging admin token to retry the migration, then it can finish QA.',
          actions: [{ label: 'Add the token', primary: true, act: 'open' }, { label: 'Why did it fail?', act: 'ask', q: 'Why did Docs search fail?' }] },
        { id: 't-pass', kind: 'fm', ref: 'f-passkey', why: 'Your call', tone: 'attention',
          text: 'About 8% of sign-ins come from devices that can’t create passkeys. Give them a magic-link fallback, or keep passwords for now?',
          replies: ['Use magic links', 'Keep passwords'], ack: 'Sent. {fm:f-passkey} is back to building the client.' },
        { id: 't-88', kind: 'pr', ref: 'f-csv', pr: 88, title: 'Review PR #88 · Ledger CSV export', why: 'Ready for review', tone: 'signal',
          text: '9 files and CI passed. I’d start with the streaming writer; that’s where the risk is.',
          actions: [{ label: 'Start review', primary: true, ack: 'Opened the walkthrough for {pr:88}. Five chapters, about 12 minutes.' }] },
        { id: 't-1284', kind: 'review', ref: 'r1284', why: 'Requested by mk', tone: 'attention',
          text: 'The walkthrough is ready (5 chapters), and 2 draft comments are waiting to post.',
          actions: [{ label: 'Review', primary: true, ack: 'Opened {r:r1284}. Your 2 drafts are on chapter 3.' }] },
        { id: 't-1291', kind: 'request', pr: 1291, title: '#1291 Rotate webhook signing keys', why: 'Requested 40 min ago', tone: 'attention',
          text: 'No walkthrough yet. I can prepare one on Dev so it’s ready when you are.',
          actions: [{ label: 'Prepare it', primary: true, ack: 'Preparing {pr:1291} on {m:dev}. I’ll tell you when it’s ready.' }] },
      ],
      chatsTitle: 'Chats waiting on you',
      chats: [
        { id: 'k-snap', ref: 'c-snap', why: 'Waiting on you · 12m', quote: 'Quarantine the 3 flaky tests, or keep retrying them?',
          replies: ['Quarantine them', 'Keep retrying'] },
        { id: 'k-hook', ref: 'c-hook', why: 'Asking permission · 40m', quote: 'May I run scripts/rotate-keys.sh against staging?',
          replies: ['Allow once', 'Not yet'] },
      ],
      notes: [
        { id: 'n-crash', tone: 'alert', who: 'w-crash',
          text: '{w:w-crash} is out. Its GitHub token expired at 3:02 AM, so it’s missed 6 runs. Want me to walk you through reconnecting it?',
          actions: [{ label: 'Fix it with me', primary: true, ack: 'Opening {w:w-crash}. Step one is signing in to GitHub again; I’ll handle the rest.' },
            { label: 'Later', act: 'snooze', ack: 'Okay. I’ll bring {w:w-crash} up again at 11.' }] },
        { id: 'n-disk', tone: 'attention',
          text: '{m:dev} is down to 9 GB. I hold new launches there below 20 GB, and I found 14 GB of finished worktrees I can clear.',
          actions: [{ label: 'Clear 14 GB', primary: true, ack: 'Cleared 14 GB on {m:dev}. It has 23 GB free now.' },
            { label: 'Show me first', act: 'route', route: 'machines:dev' }] },
      ],
      moving: '{fm:f-retry} is building, {fm:f-snap} is in QA and {fm:f-cache} is in review. {fm:f-deeplink} is ready to plan whenever you are.',
      recapTitle: 'While you were away',
      recap: [
        { t: '1:20 AM', ic: 'pull', text: '{fm:f-csv} opened {pr:88}. CI passed.' },
        { t: '2:00 AM', ic: 'eye', text: '{w:w-sims} deleted 3 idle simulators.' },
        { t: '2:14 AM', ic: 'alert', tone: 'alert', text: '{fm:f-docs} got blocked in QA.' },
        { t: '3:02 AM', ic: 'alert', tone: 'alert', text: '{w:w-crash} stopped: its GitHub token expired.' },
        { t: '6:00 AM', ic: 'eye', text: '{w:w-deps} found 3 updates.' },
        { t: '6:40 AM', ic: 'box', text: 'Lumen 4.12.0 (0640) is ready to install.' },
        { t: '7:00 AM', ic: 'sun', text: '{w:w-brief} wrote your morning brief.' },
      ],
      later: [
        { t: '9:30 AM', text: '{w:w-ci} checks the release branch.' },
        { t: '3:00 PM', text: 'Deploy window, from your morning brief.' },
        { t: '4:00 PM', text: '{w:w-notes} would draft release notes, but it’s paused.' },
      ],
      suggest: ['What did I miss overnight?', 'Plan my morning', 'What’s everyone working on?'],
      answers: [
        { k: /miss|overnight|away|night/i, a: 'Overnight, {fm:f-csv} opened {pr:88} and {w:w-deps} found 3 updates. Two things broke: {fm:f-docs} got blocked at 2:14 AM, and {w:w-crash} lost its GitHub token at 3:02 AM. Nothing shipped.' },
        { k: /plan|morning|day|start/i, a: 'Here’s a 20-minute start: unblock {fm:f-docs} (2 min), answer {fm:f-passkey} (1 min), then review {pr:88} (about 12 min). After that, {fm:f-deeplink} is ready to plan if you want something new going before lunch.' },
        { k: /docs|fail|token|why/i, a: 'The staging admin API returned a 401 when {fm:f-docs} ran the migration. The token in its environment expired yesterday. Paste a new one in its window and it retries on its own.' },
        { k: /working|everyone|running|status|doing/i, a: '{fm:f-retry} is wiring the 503 path with 2 agents, {fm:f-snap} is re-running 40 snapshot tests, and {fm:f-cache} is in review on {m:studio}. All three look healthy.' },
      ],
    },

    afternoon: {
      label: 'Afternoon',
      note: '1:42 PM. You cleared the morning list. One question is waiting, and the assistant connected two things for you.',
      greeting: 'Good afternoon.',
      when: 'Friday, October 2 · 1:42 PM',
      away: 'Last here 25 minutes ago',
      mood: 'calm',
      overrides: {
        features: {
          'f-docs': { hud: 'working', step: 4, now: 'PR #96 is open; CI is running' },
          'f-passkey': { hud: 'working', step: 1, stepNote: 'client', now: 'Building the magic-link fallback' },
          'f-csv': { hud: 'done', step: 5, now: 'Merged' },
          'f-retry': { hud: 'turn', step: 1, now: 'Choosing a retry cap', say: 'How many retries before giving up?' },
        },
        machines: { dev: { health: 'healthy' } },
        watchers: { 'w-crash': { attention: null } },
      },
      lead: [
        'You’re in a good rhythm. Since this morning {fm:f-docs} got unstuck and opened its PR, and you approved {pr:88}.',
        'Just one question is waiting on you.',
      ],
      topTitle: 'Waiting on you',
      top: [
        { id: 't-retry', kind: 'fm', ref: 'f-retry', why: 'Your call', tone: 'attention',
          text: 'Retry-After works for 429s and 503s now. How many retries before giving up: 3 or 5?',
          replies: ['3 retries', '5 retries'], ack: 'Sent. {fm:f-retry} is finishing the backoff tests.' },
      ],
      chatsTitle: 'Worth a look',
      chats: [
        { id: 'k-index', ref: 'c-index', why: 'Finished 5 min ago', quote: 'Rebuilt the ledger index. Queries are 4× faster. Summary’s in the chat.',
          actions: [{ label: 'Read summary', act: 'route', route: 'chats:c-index' }] },
      ],
      notes: [
        { id: 'n-ci', tone: 'info', who: 'w-ci',
          text: '{w:w-ci} found 2 new failures on lumen-ios. Both are in the snapshot files {fm:f-snap} is already fixing, so I passed them along instead of interrupting you.',
          actions: [{ label: 'Show me', act: 'route', route: 'watchers:w-ci' }, { label: 'Thanks', act: 'dismiss', ack: 'Anytime.' }] },
        { id: 'n-merged', tone: 'good',
          text: '{pr:88} merged a few minutes ago. That’s the second thing shipped today, after {fm:f-theme}.', actions: [] },
      ],
      moving: '{fm:f-passkey} is building the client, {fm:f-docs} has {pr:96} open, {fm:f-snap} is in QA and {fm:f-cache} is in review.',
      recapTitle: 'Since this morning',
      recap: [
        { t: '9:06 AM', ic: 'check', text: 'You unblocked {fm:f-docs}.' },
        { t: '9:08 AM', ic: 'check', text: 'You chose magic links for {fm:f-passkey}.' },
        { t: '9:12 AM', ic: 'disk', text: 'I cleared 14 GB on {m:dev}.' },
        { t: '9:40 AM', ic: 'eye', text: '{w:w-crash} is back online.' },
        { t: '10:05 AM', ic: 'check', text: 'You approved {pr:88}.' },
        { t: '1:20 PM', ic: 'checkCircle', tone: 'signal', text: '{fm:f-csv} merged.' },
      ],
      later: [
        { t: '3:00 PM', text: 'Deploy window.' },
        { t: '4:00 PM', text: '{w:w-notes} is paused, so no release notes today.' },
        { t: '9:00 PM', text: '{w:w-oncall} reads #oncall.' },
      ],
      suggest: ['What changed since this morning?', 'Anything to check before the deploy?', 'Start something new'],
      answers: [
        { k: /changed|since|morning/i, a: 'You unblocked {fm:f-docs}, answered {fm:f-passkey} and approved {pr:88}, which merged at 1:20 PM. I cleared 14 GB on {m:dev}, and {w:w-crash} is back online.' },
        { k: /deploy|check|before/i, a: 'Before 3 PM: {pr:96} from {fm:f-docs} needs one approval, and {w:w-ci} is green apart from the 2 snapshot tests {fm:f-snap} is fixing. I’d leave the snapshot work out of this deploy.' },
        { k: /new|start/i, a: '{fm:f-deeplink} is ready to plan. Want me to draft a plan for it? You’d just approve it.' },
      ],
    },

    clear: {
      label: 'All clear',
      note: 'Friday, 6:10 PM. Nothing needs you. The assistant suggests what you could do next instead of saying “all clear”.',
      greeting: 'Good evening.',
      when: 'Friday, October 2 · 6:10 PM',
      away: 'Last here an hour ago',
      mood: 'happy',
      overrides: {
        features: {
          'f-docs': { hud: 'done', step: 5, now: 'Merged' },
          'f-passkey': { hud: 'working', step: 2, now: 'A reviewer is checking the client' },
          'f-csv': { hud: 'done', step: 5, now: 'Merged' },
          'f-snap': { hud: 'done', step: 5, now: 'Merged' },
        },
        machines: { dev: { health: 'healthy' } },
        watchers: { 'w-crash': { attention: null } },
      },
      lead: [
        'You’re all caught up. {fm:f-retry}, {fm:f-passkey} and {fm:f-cache} are working on their own, and nothing needs you until {w:w-oncall} runs at 9.',
        'If you have a few minutes before the weekend, here are some ideas.',
      ],
      topTitle: 'If you have a minute',
      suggestions: true,
      top: [
        { id: 's-plan', kind: 'suggest', ref: 'f-deeplink', title: 'Plan Deep link router', why: 'Ready since yesterday', tone: 'accent',
          text: 'I can draft the plan tonight so it’s waiting for you Monday. You’d just approve it.',
          actions: [{ label: 'Draft the plan', primary: true, ack: 'Drafting a plan for {fm:f-deeplink}. It’ll be waiting Monday morning.' },
            { label: 'Not this week', act: 'snooze', ack: 'Okay. I’ll ask again Monday.' }] },
        { id: 's-1291', kind: 'request', pr: 1291, title: 'Prepare #1291 Rotate webhook signing keys', why: 'Requested by ao', tone: 'accent',
          text: 'A walkthrough tonight means about 10 minutes of reviewing on Monday instead of 40.',
          actions: [{ label: 'Prepare it', primary: true, ack: 'Preparing {pr:1291} on {m:dev}. It’ll be ready Monday.' }] },
        { id: 's-notes', kind: 'watcher', ref: 'w-notes', title: 'Release notes for 4.12', why: 'Watcher paused', tone: 'accent',
          text: '{w:w-notes} has been paused for 5 days, and 4.12.0 shipped today. Want a draft from the merged PRs?',
          actions: [{ label: 'Draft them now', primary: true, ack: 'On it. {w:w-notes} is drafting notes for 4.12.0.' },
            { label: 'Turn the watcher back on', ack: '{w:w-notes} is back on. Next run: Friday at 4:00 PM.' }] },
      ],
      chatsTitle: 'Pick up where you left off',
      chats: [
        { id: 'k-copy', ref: 'c-copy', why: 'You stopped mid-draft · 3h', quote: 'Screen 2 of 5 done. Next: the permissions screen.',
          actions: [{ label: 'Resume', act: 'route', route: 'chats:c-copy' }] },
      ],
      notes: [
        { id: 'n-week', tone: 'good',
          text: 'Good week: 4 features shipped and 11 reviews done, and {w:w-brief} didn’t miss a morning. {fm:f-csv} and {fm:f-docs} both merged today.', actions: [] },
      ],
      moving: '{fm:f-retry} is wiring the 503 path, {fm:f-passkey} is in review and {fm:f-cache} is in review on {m:studio}. All three look healthy.',
      recapTitle: 'Today',
      recap: [
        { t: '10:05 AM', ic: 'check', text: 'You approved {pr:88}.' },
        { t: '1:20 PM', ic: 'checkCircle', tone: 'signal', text: '{fm:f-csv} merged.' },
        { t: '3:00 PM', ic: 'box', text: 'Lumen 4.12.0 went out in the deploy window.' },
        { t: '4:45 PM', ic: 'checkCircle', tone: 'signal', text: '{fm:f-docs} merged.' },
        { t: '5:30 PM', ic: 'checkCircle', tone: 'signal', text: '{fm:f-snap} merged.' },
      ],
      later: [
        { t: '9:00 PM', text: '{w:w-oncall} reads #oncall.' },
        { t: '2:00 AM', text: '{w:w-sims} cleans up idle simulators.' },
        { t: 'Mon 7:00 AM', text: '{w:w-brief} writes your morning brief.' },
      ],
      suggest: ['Wrap up my week', 'What runs over the weekend?', 'Start something new'],
      answers: [
        { k: /week|wrap/i, a: 'This week: 4 features shipped (Theme tokens, Ledger CSV export, Docs search, Snapshot test flakes), 11 reviews, and 2 new watchers. Still open: {fm:f-retry}, {fm:f-passkey} and {fm:f-cache}.' },
        { k: /weekend|runs|overnight/i, a: '{w:w-sims} runs nightly at 2 AM, and {w:w-ci} keeps checking every 30 minutes. {fm:f-retry} should finish tonight; I’ll hold its PR until Monday so it doesn’t ping anyone.' },
        { k: /new|start/i, a: '{fm:f-deeplink} is ready to plan. Want me to draft a plan for it? You’d just approve it.' },
      ],
    },

    trouble: {
      label: 'Something broke',
      note: '8:40 PM. A machine went offline and another ran out of space. The assistant leads with a plan.',
      greeting: 'Heads up.',
      when: 'Friday, October 2 · 8:40 PM',
      away: 'Last here 2 hours ago',
      mood: 'concerned',
      overrides: {
        features: {
          'f-csv': { hud: 'blocked', step: 4, now: 'Can’t save progress: Dev’s disk is full' },
          'f-cache': { offline: true, now: 'Last known: a reviewer was checking the LRU change' },
          'f-docs': { hud: 'working', step: 4, now: 'PR #96 is open' },
        },
        machines: { studio: { state: 'offline' }, dev: { health: 'storage_full' } },
        watchers: { 'w-crash': { attention: 'Failed twice: the GitHub token expired' }, 'w-disk': { offline: true } },
      },
      lead: [
        'Two machines need you before anything else. {m:studio} went offline 25 minutes ago, and {m:dev} is out of space, so {fm:f-csv} can’t save its progress.',
        'Nothing’s lost. The rest is paused safely until these are fixed.',
      ],
      topTitle: 'Fix these first',
      top: [
        { id: 't-dev', kind: 'machine', ref: 'dev', title: 'Free up space on Dev', why: 'Disk full · 1 GB left', tone: 'alert',
          text: 'I found 31 GB I can clear safely: 22 GB of finished worktrees and 9 GB of simulator caches. {fm:f-csv} and {r:r311} pick up on their own after.',
          actions: [{ label: 'Clear 31 GB', primary: true, ack: 'Cleared 31 GB on {m:dev}. {fm:f-csv} is saving again, and I’m retrying {r:r311}.' },
            { label: 'Show me first', act: 'route', route: 'machines:dev' }] },
        { id: 't-studio', kind: 'machine', ref: 'studio', title: 'Studio is offline', why: 'Last seen 25m ago', tone: 'alert',
          text: '{fm:f-cache} was mid-review there. I can move it to {m:work}, or wait for Studio to come back.',
          actions: [{ label: 'Move it to Work', primary: true, ack: 'Moving {fm:f-cache} to {m:work}. It restarts its review from the last checkpoint.' },
            { label: 'Wait for Studio', act: 'snooze', ack: 'I’ll wait, and tell you when {m:studio} is back.' }] },
        { id: 't-pass', kind: 'fm', ref: 'f-passkey', why: 'Your call', tone: 'attention',
          text: 'About 8% of sign-ins come from devices that can’t create passkeys. Give them a magic-link fallback, or keep passwords for now?',
          replies: ['Use magic links', 'Keep passwords'], ack: 'Sent. {fm:f-passkey} is back to building the client.' },
      ],
      chatsTitle: 'Chats waiting on you',
      chats: [
        { id: 'k-snap', ref: 'c-snap', why: 'Waiting on you · 12m', quote: 'Quarantine the 3 flaky tests, or keep retrying them?',
          replies: ['Quarantine them', 'Keep retrying'] },
        { id: 'k-hook', ref: 'c-hook', why: 'Asking permission · 40m', quote: 'May I run scripts/rotate-keys.sh against staging?',
          replies: ['Allow once', 'Not yet'] },
      ],
      notes: [
        { id: 'n-crash', tone: 'alert', who: 'w-crash',
          text: '{w:w-crash} failed twice in a row because its GitHub token expired. I paused it so it stops retrying.',
          actions: [{ label: 'Reconnect GitHub', primary: true, ack: 'Opening {w:w-crash}. Sign in to GitHub and I’ll resume it.' },
            { label: 'Later', act: 'snooze', ack: 'Okay. It stays paused until you’re ready.' }] },
        { id: 'n-311', tone: 'info',
          text: '{r:r311} couldn’t be prepared for the same reason: no space on {m:dev}. I’ll retry it once there’s room.', actions: [] },
      ],
      moving: '{fm:f-retry} and {fm:f-snap} are fine on {m:work}, and {fm:f-docs} has {pr:96} open.',
      recapTitle: 'In the last hour',
      recap: [
        { t: '8:12 PM', ic: 'check', text: '{fm:f-cache} saved a checkpoint on {m:studio}.' },
        { t: '8:15 PM', ic: 'alert', tone: 'alert', text: '{m:studio} stopped responding.' },
        { t: '8:31 PM', ic: 'disk', tone: 'alert', text: '{m:dev} ran out of space. {fm:f-csv} paused.' },
        { t: '8:33 PM', ic: 'alert', tone: 'alert', text: '{r:r311} couldn’t check out its branch.' },
        { t: '8:36 PM', ic: 'eye', text: 'I paused {w:w-crash} after its second failure.' },
      ],
      later: [
        { t: '9:00 PM', text: '{w:w-oncall} reads #oncall.' },
        { t: '2:00 AM', text: '{w:w-sims} cleans up simulators, which frees space on {m:work} only.' },
      ],
      suggest: ['What happened?', 'Is anything lost?', 'Fix what you can'],
      answers: [
        { k: /happen|what/i, a: '{m:studio} stopped responding at 8:15 PM. At 8:31 PM {m:dev} ran out of space, which paused {fm:f-csv} and made {r:r311} fail to check out. Separately, {w:w-crash} has an expired GitHub token.' },
        { k: /lost|safe|data/i, a: 'Nothing’s lost. {fm:f-csv} stopped before writing anything, and {fm:f-cache}’s last checkpoint on {m:studio} is from 8:12 PM. Nothing needs redoing.' },
        { k: /fix|can|do it/i, a: 'I can clear 31 GB on {m:dev} and move {fm:f-cache} to {m:work} right now. Use the buttons under “Fix these first”, or say “do both”.' },
        { k: /both/i, a: 'Done. I cleared 31 GB on {m:dev} and moved {fm:f-cache} to {m:work}.', resolves: ['t-dev', 't-studio'] },
      ],
    },
  };

  window.HOME = { MOMENTS };
})();
