/* Entirely synthetic fixtures. No captured Active Work records. */
window.makeFirstMateData = function () {
  const make = (id,title,key,kind,goal,stage,attention=false) => ({
    id,title,key,kind,goal,stage,attention,paused:false,progress:0,
    messages:[{who:'user',text:kind==='review'?'Assess this PR and have an architect check any design risks.':'QA found an edge case. Fix it, then get an architect review before we return to QA.'},{who:'mate',text:kind==='review'?'I’ve connected the review to this feature. The architect is checking the change and its test coverage.':'The fix is complete. Architect review 2 is running, then QA will verify it.',route:true},{who:'mate',text:'I’ll bring back any findings that need your input.'}],
    agents:[{id:id+'-architect',name:'Architect',role:'Design and code review',step:'Review 2',model:'Deep model',state:'Running',closed:false,initial:'A',tone:'violet',doc:'review'},{id:id+'-coder',name:'Coder',role:'Implementation',step:'Restore fix',model:'Fast model',state:'Complete',closed:false,initial:'C',tone:'green',doc:'fix'},{id:id+'-qa',name:'QA',role:'Verification',step:'QA 1',model:'Fast model',state:'Issue found',closed:false,initial:'Q',tone:'amber',doc:'evidence'},{id:id+'-planner',name:'Planner',role:'Approach and tradeoffs',step:'Plan 1',model:'Deep model',state:'Complete',closed:true,initial:'P',tone:'slate',doc:'plan'}],
    docs:[
      {id:'plan',title:'Approach and tradeoffs',filename:'approach.md',type:'Plans',agent:'Planner',step:'Plan 1',time:'Yesterday',description:'Scope, constraints, and the proposed approach.',sections:[['The goal',goal],['Approach','Keep the existing user flow intact. Introduce the change behind a small, testable boundary and preserve the previous behavior when data is missing.'],['Tradeoffs','Prefer an explicit fallback over silently dropping state. Keep the shared contract compatible while each client is updated.'],['Verification','Exercise the normal path, missing-data path, and interrupted operation. Record evidence before requesting proof review.']]},
      {id:'fix',title:'Edge-case fix',filename:'fix-summary.md',type:'Notes',agent:'Coder',step:'Restore fix',time:'10:42',description:'What changed and how it was checked.',sections:[['What changed','Added a fallback for an incomplete response and preserved the pending user action.'],['Validation','The focused regression case and existing behavior checks pass in this simulated example.'],['Next','An architect reviews the change before a fresh QA attempt.']]},
      {id:'evidence',title:'QA findings',filename:'qa-evidence.md',type:'Evidence',agent:'QA',step:'QA 1',time:'10:18',description:'Reproduction steps and evidence for the edge case.',sections:[['Finding','An interrupted operation can leave the view without its latest state.'],['Reproduction','Start the operation, interrupt it before completion, then return to the view. The pending state should remain available.'],['Expected result','The user can continue without recreating their work.'],['Follow-up','A focused fix and another review were added to this feature’s route.']]},
      {id:'review',title:'Architecture review',filename:'architecture-review.md',type:'Reviews',agent:'Architect',step:'Review 2',time:'Now',draft:true,description:'Review of the fix, contracts, and test coverage.',sections:[['Review in progress','Checking the implementation against the agreed approach and the original QA finding.'],['Scope','Compatibility, state ownership, error handling, and focused regression coverage.']]}
    ],
    events:[{id:'review',time:'Now',title:'Architect review 2',body:'Checking the fix before QA resumes.',agent:'Architect',step:'Review 2',model:'Deep model',tone:'violet',status:'Running',doc:'review'},{id:'fix',time:'10:42',title:'Edge-case fix completed',body:'Added fallback handling and focused tests.',agent:'Coder',step:'Restore fix',model:'Fast model',tone:'green',doc:'fix'},{id:'qa',time:'10:18',title:'QA found an edge case',body:'A fix and another review were added to the route.',agent:'QA',step:'QA 1',tone:'amber',doc:'evidence'},{id:'plan',time:'Yesterday',title:'Plan approved',body:'Approach and technical explainer recorded.',agent:'Planner',step:'Plan 1',tone:'green',doc:'plan'}]
  });
  const a=make('api-guard','API change guard','MOB-204','feature','Catch mobile API compatibility risks before a server change ships.','Architect review 2');
  a.messages[0].text='The API guard found a missing-field edge case. Fix it, then have an architect review before QA runs again.';
  const b=make('conversation-titles','Conversation titles','MOB-218','feature','Make conversation titles easy to rename without interrupting the chat.','Your proof review',true);b.progress=2;b.agents[0].state='Complete';b.agents.push({...b.agents[2],id:b.id+'-qa2',name:'QA 2',step:'QA 2',state:'Complete',doc:'evidence-2'});b.messages=[{who:'user',text:'Keep the title editable in place and make keyboard behavior feel natural.'},{who:'mate',text:'The change and QA pass are ready. Your proof review is the last checkpoint before the PR.',route:true}];b.events.unshift({id:'proof',time:'Now',title:'Ready for your proof review',body:'Keyboard, empty-title, and interrupted-edit paths have been checked.',agent:'QA',step:'QA 2',tone:'amber',doc:'evidence'});b.docs[3].draft=false;b.docs[3].sections=[['Review passed','The title editing behavior and keyboard handling satisfy the agreed approach.']];b.events.forEach(e=>{if(e.status==='Running')e.status='Complete'});b.events[0].agent='QA 2';b.events[0].doc='evidence-2';b.docs.push({id:'evidence-2',title:'QA 2 verification',filename:'qa-2-evidence.md',type:'Evidence',agent:'QA 2',step:'QA 2',time:'Now',description:'Proof for the fresh verification pass.',sections:[['QA 2 passed','Keyboard, empty-title, and interrupted-edit behavior pass in this sample.'],['Earlier attempt','The original finding remains in QA findings.']]});
  const c=make('build-readiness','Build readiness','PR-342','review','Check the toolchain update and preserve the existing build and test coverage.','Assess the PR');c.agents[0].step='PR assessment';c.agents[1].closed=true;
  const d=make('package-cleanup','Package cleanup','MOB-231','feature','Clarify package boundaries while preserving the public interfaces.','Plan and decision',true);d.progress=-1;d.agents=d.agents.filter(a=>a.name==='Planner');d.agents[0].closed=false;d.agents[0].state='Waiting';d.docs=d.docs.filter(x=>x.id==='plan');d.events=d.events.filter(x=>x.id==='plan');d.events[0].title='Approach ready for a decision';d.events[0].tone='amber';d.messages=[{who:'user',text:'Map the package boundaries and propose a small first step.'},{who:'mate',text:'I recommend moving the shared types first. The plan is ready for your review; the larger dependency changes can remain a separate step.'}];
  const e=make('first-mate','First Mate workspace','','idea','Give every feature a clear conversation, a connected journal, and a visible crew.','Explore');e.progress=-1;e.attention=false;e.agents=e.agents.filter(a=>a.name==='Planner');e.agents[0].closed=false;e.agents[0].state='Running';e.agents[0].step='Explore';e.docs=e.docs.filter(x=>x.id==='plan');e.events=[{id:'explore',time:'Today',title:'Direction captured',body:'A light and dark feature workspace, with Timeline and Graph under Workflow.',agent:'Planner',step:'Explore',tone:'violet',doc:'plan'}];e.messages=[{who:'user',text:'Keep the feature journal layout. The goal and a small agent summary belong in Overview.'},{who:'mate',text:'The direction is recorded. We can explore the interaction here and keep each decision connected to its feature.'}];
  return window.upgradeFirstMateData([a,b,c,d,e]);
};

/* Idempotent fixture upgrade also enriches an existing browser's saved demo. */
window.upgradeFirstMateData = function (features) {
  const f = features.find(f => f.id === 'api-guard');
  if (!f || f.associationVersion === 2) return features;
  const reviewing = f.progress === 0;
  const specs = [
    ['scope', 'Scope planner', 'Plan 1', 'P', 'slate', 'Define the smallest compatible change.', 'The scope keeps decoding behavior stable and isolates fallback handling.'],
    ['contract-plan', 'Contract planner', 'Plan 1', 'C', 'slate', 'Map shared API assumptions across clients.', 'The contract map identifies optional fields and the compatibility boundary.'],
    ['test-plan', 'Test planner', 'Plan 1', 'T', 'slate', 'Plan missing-field and interrupted-operation coverage.', 'The test matrix covers normal completion, incomplete data, and interruption.'],
    ['decoder', 'Decoder implementer', 'Implementation', 'D', 'green', 'Implement tolerant response decoding.', 'Optional values preserve their documented defaults.'],
    ['state', 'State implementer', 'Implementation', 'S', 'green', 'Preserve pending state across interruptions.', 'The pending action remains owned by the feature until completion.'],
    ['fixtures', 'Fixture author', 'Implementation', 'F', 'green', 'Build synthetic response fixtures.', 'Fixtures include omitted fields, empty results, and a successful response.'],
    ['client', 'Client integrator', 'Implementation', 'C', 'green', 'Connect the fallback to the client boundary.', 'The client handles the fallback without changing the visible flow.'],
    ['regression', 'Regression author', 'Implementation', 'R', 'green', 'Add focused behavior checks.', 'The original completion behavior remains covered alongside the new fallback.'],
    ['qa-contract', 'Contract verifier', 'QA 1', 'C', 'amber', 'Verify compatibility with older response shapes.', 'Older shapes pass. The interrupted operation needs a targeted fix.'],
    ['qa-interruption', 'Interruption verifier', 'QA 1', 'I', 'amber', 'Exercise cancellation and reopening.', 'Reopening exposed the pending-state edge case recorded by QA.'],
    ['qa-normal', 'Normal-flow verifier', 'QA 1', 'N', 'green', 'Verify the normal completion path.', 'Normal completion passes with no visible behavior change.'],
    ['qa-accessibility', 'Accessibility verifier', 'QA 1', 'A', 'green', 'Check focus and status announcements.', 'Focus remains stable and state changes have a readable announcement.'],
    ['fix-state', 'State repair', 'Restore fix', 'S', 'green', 'Repair the interrupted-state boundary.', 'The pending action survives a canceled response.'],
    ['fix-tests', 'Fix regression tests', 'Restore fix', 'T', 'green', 'Reproduce and cover the QA finding.', 'The reproduction fails before the fix and passes after it.'],
    ['fix-contract', 'Fallback integrator', 'Restore fix', 'F', 'green', 'Check that the fix preserves the shared contract.', 'Fallback handling leaves the public response shape unchanged.'],
    ['security', 'Security reviewer', 'Review 2', 'S', 'violet', 'Review input handling, trust boundaries, and accidental data exposure.', 'No new trust boundary is introduced. Error details stay within the feature.'],
    ['concurrency', 'Concurrency reviewer', 'Review 2', 'C', 'violet', 'Review cancellation, task lifetime, and state ownership.', 'Checking the cancellation window between receiving data and committing state.'],
    ['compatibility', 'API compatibility reviewer', 'Review 2', 'A', 'violet', 'Review missing fields and compatibility with existing clients.', 'The missing-field path uses an explicit default and preserves older clients.'],
    ['coverage', 'Test coverage reviewer', 'Review 2', 'T', 'violet', 'Review regression coverage and whether assertions prove behavior.', 'The regression reproduces the original finding and exercises normal completion.'],
    ['performance', 'Performance reviewer', 'Review 2', 'P', 'violet', 'Review repeated work, allocations, and response latency.', 'Checking that fallback handling does not repeat a request or decode twice.'],
    ['simplicity', 'Simplicity reviewer', 'Review 2', 'S', 'violet', 'Review unnecessary abstraction and clarity of the fix.', 'The change stays within the existing boundary and needs no additional layer.']
  ];
  for (const [key,name,step,initial,tone,brief,result] of specs) {
    const id = f.id + '-' + key, doc = key + '-notes';
    const running = reviewing && ['concurrency','performance'].includes(key);
    if (!f.agents.some(a => a.id === id)) f.agents.push({id,name,step,initial,tone,brief,result,
      role:brief.replace(/\.$/,''),model:step==='Review 2'?'Deep model':'Fast model',
      state:running?'Running':'Complete',closed:['scope','contract-plan','test-plan','security'].includes(key),doc});
    if (!f.docs.some(d => d.id === doc)) f.docs.push({id:doc,title:name.replace(/ reviewer$/,' review'),
      filename:key+'-notes.md',type:step==='Review 2'?'Reviews':step==='Plan 1'?'Plans':step==='QA 1'?'Evidence':'Notes',
      agent:name,agentId:id,step,time:running?'Now':'10:48',draft:running,description:brief,
      sections:[['Assignment',brief],['Findings',result],['Evidence','This independent session reviewed the synthetic API guard change and its linked plan, fix, and QA finding.']]});
  }
  if (!f.docs.some(d=>d.id==='review-checklist')) f.docs.push({id:'review-checklist',title:'Review coverage checklist',filename:'review-coverage.md',type:'Reviews',agent:'Architect',agentId:f.id+'-architect',step:'Review 2',time:'Now',description:'Seven independent review perspectives and their handoff criteria.',sections:[['Seven perspectives','Architecture, security, concurrency, API compatibility, test coverage, performance, and simplicity. Each reviewer has an independent session.'],['Handoff','All seven reviews must finish and blocking findings must be addressed before the next QA pass.'],['Attached context','The approach, fix summary, and original QA evidence remain associated with their own workflow steps.']]});
  const architect=f.agents.find(a=>a.id===f.id+'-architect');
  if(architect){architect.brief='Review state ownership and the shared contract. Reconcile the seven independent findings before QA continues.';architect.result='The architecture is consistent with the plan. Waiting for the concurrency and performance reviews before the final handoff.';}
  const review=f.events.find(e=>e.id==='review');
  if(review)review.body='Seven independent reviews cover architecture, security, concurrency, compatibility, tests, performance, and simplicity.';
  if(!f.events.some(e=>e.id==='implementation'))f.events.splice(Math.max(0,f.events.findIndex(e=>e.id==='plan')),0,{id:'implementation',time:'09:35',title:'Implementation completed',body:'Five sessions delivered the decoder, state handling, fixtures, integration, and regression checks.',agent:'Decoder implementer',step:'Implementation',tone:'green'});
  f.associationVersion=2;
  return features;
};
